# 切记保存为UTF-8类型.
spring:
  profiles:
    active:
    - dev # 开发环境

---
server:
  port: 7001 #注册中心占用7001端口号,冒号后面必须要有空格。

spring:
  profiles: dev 
  application: microservicecloud-config-eureka-client-7001


eureka:
  instance: 
    hostname: eureka7001.com #eureka服务端的实例名称，冒号后面必须要有空格。
  client:
    register-with-eureka: false # false表示不向注册中心注册自己
    fetch-registry: false # false表示自己端就是注册中心,我的职责就是维护服务实例,并不需要去检索服务
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/        
      defaultZone: http://127.0.0.1:7001/eureka/  

---
server:
  port: 7001 #注册中心占用7001端口号,冒号后面必须要有空格。

spring:
  profiles: test 
  application: microservicecloud-config-eureka-client-7001

eureka:
  instance: 
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false # false表示不向注册中心注册自己
    fetch-registry: false # false表示自己端就是注册中心,我的职责就是维护服务实例,并不需要去检索服务
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/        
      defaultZone: http://127.0.0.1:7001/eureka/   
      
    
        